Hospital Management System
Using SQL (SQLite) in Google Colab

This project is a Hospital Management System built using SQL and Python in Google Colab.
It manages patients, doctors, appointments, and treatments using a relational database.

The system demonstrates how data is stored, connected, and retrieved using SQL queries.

In [ ]:

# Create database connection
import sqlite3

conn = sqlite3.connect('hospital.db')
cursor = conn.cursor()

print("Database created successfully")

# Create Patients table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Patients (
    patient_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    gender TEXT,
    contact TEXT
)
""")
# Create Doctors table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Doctors (
    doctor_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    specialization TEXT,
    contact TEXT
)
""")
# Create Appointments table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Appointments (
    appointment_id INTEGER PRIMARY KEY,
    patient_id INTEGER,
    doctor_id INTEGER,
    date TEXT,
    FOREIGN KEY(patient_id) REFERENCES Patients(patient_id),
    FOREIGN KEY(doctor_id) REFERENCES Doctors(doctor_id)
)
""")
# Create Treatments table
cursor.execute("""
CREATE TABLE IF NOT EXISTS Treatments (
    treatment_id INTEGER PRIMARY KEY,
    appointment_id INTEGER,
    description TEXT,
    cost REAL,
    FOREIGN KEY(appointment_id) REFERENCES Appointments(appointment_id)
)
""")
conn.commit()
#Entering Data
#Sample data is inserted into all tables to simulate real hospital records.
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())
cursor.execute("INSERT OR IGNORE INTO Patients VALUES (1, 'Ali', 25, 'Male', '03001234567')")
cursor.execute("INSERT OR IGNORE INTO Patients VALUES (2, 'Sara', 30, 'Female', '03007654321')")
cursor.execute("INSERT OR IGNORE INTO Doctors VALUES (1, 'Dr Ahmed', 'Cardiologist', '03111222333')")
cursor.execute("INSERT OR IGNORE INTO Doctors VALUES (2, 'Dr Khan', 'Dermatologist', '03222333444')")
cursor.execute("INSERT OR IGNORE INTO Appointments VALUES (1, 1, 1, '2026-04-01')")
cursor.execute("INSERT OR IGNORE INTO Appointments VALUES (2, 2, 2, '2026-04-02')")
cursor.execute("INSERT OR IGNORE INTO Treatments VALUES (1, 1, 'Heart Checkup', 5000)")
cursor.execute("INSERT OR IGNORE INTO Treatments VALUES (2, 2, 'Skin Treatment', 3000)")
conn.commit()
for row in cursor.execute("SELECT * FROM Patients"):
    print(row)
query = """
SELECT
    Patients.name AS Patient_Name,
    Doctors.name AS Doctor_Name,
    Appointments.date AS Appointment_Date
FROM Appointments
JOIN Patients ON Patients.patient_id = Appointments.patient_id
JOIN Doctors ON Doctors.doctor_id = Appointments.doctor_id
"""

for row in cursor.execute(query):
    print(row)
    import pandas as pd

df = pd.read_sql_query(query, conn)
df

Database created successfully
[('Patients',), ('Doctors',), ('Appointments',), ('Treatments',)]
(1, 'Ali', 25, 'Male', '03001234567')
(2, 'Sara', 30, 'Female', '03007654321')
('Ali', 'Dr Ahmed', '2026-04-01')
('Sara', 'Dr Khan', '2026-04-02')

  Patient_Name Doctor_Name Appointment_Date
0          Ali    Dr Ahmed       2026-04-01
1         Sara     Dr Khan       2026-04-02

Basic Query: Display all patients

This query retrieves all records from the Patients table.

In [ ]:
for row in cursor.execute("SELECT * FROM Patients"):
    print(row)

(1, 'Ali', 25, 'Male', '03001234567')
(2, 'Sara', 30, 'Female', '03007654321')

Instead of plain print, use pandas:

In [ ]:
import pandas as pd

df = pd.read_sql_query("SELECT * FROM Patients", conn)
df

   patient_id  name  age  gender      contact
0           1   Ali   25    Male  03001234567
1           2  Sara   30  Female  03007654321

In [ ]:
for row in cursor.execute(query):
    print(row)
    import pandas as pd

df = pd.read_sql_query(query, conn)
df

('Ali', 'Dr Ahmed', '2026-04-01')
('Sara', 'Dr Khan', '2026-04-02')

  Patient_Name Doctor_Name Appointment_Date
0          Ali    Dr Ahmed       2026-04-01
1         Sara     Dr Khan       2026-04-02